- hosts: all
  roles:
          - cluster

- hosts: masternode
  tasks:
          - name: Setting Up Flannel for Tunneling
            shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
            become: false

          - name: Getting join command
            shell: "kubeadm token create --print-join-command"
            register: join

- hosts: slavenode
  tasks:
          - name: Executing Join Command
            command: "{{ hostvars[item]['join']['stdout'] }}"
            with_items: "{{ groups['masternode'] }}"
            ignore_errors: yes

            
- hosts: masternode
  tasks:
          - name: Copying Wordpress Deployment File
            copy:
                    src: "./wp-sql-dep.yml"
                    dest: "./"
          - name: Setting Up Wordpress server
            command: "kubectl apply -f wp-sql-dep.yml"
            become: false
