---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-frontend
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: 'wpapp'
          image: 'wordpress'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server-backend
  labels:
    app: web1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web1
  template:
    metadata:
      labels:
        app: web1
    spec:
      containers:
        - name: 'mysql'
          image: 'mysql:latest'
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: redhat
          - name: MYSQL_DATABASE
            value: wordpress-db
          - name: MYSQL_USER
            value: aditya
          - name: MYSQL_PASSWORD
            value: passwd123 
---
apiVersion: v1
kind: Service
metadata:
  name: webloader-wp
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - targetPort: 80
      port: 8080
      nodePort: 30400  
